name: hassfest

on:
  push:
  pull_request:
  schedule:
    - cron: 0 0 * * *

permissions: {}

jobs:
  validate:
    name: hassfest
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - uses: actions/checkout@v3
      - uses: home-assistant/actions/hassfest@master
